-- =============================================================
-- 3. Tablas de seguridad y control de acceso
-- =============================================================

CREATE TABLE public.rol (
    rol_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_nombre public.rol_nombre_enum NOT NULL UNIQUE
);

CREATE TABLE public.usuario (
    usuario_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_run varchar(20) NOT NULL UNIQUE,
    usuario_apellido_paterno varchar(100) NOT NULL,
    usuario_apellido_materno varchar(100),
    usuario_nombres varchar(100) NOT NULL,
    usuario_correo varchar(150) NOT NULL UNIQUE,
    usuario_estado_cuenta public.usuario_estado_enum NOT NULL DEFAULT 'activo',
    usuario_contrasena varchar(255) NOT NULL,
    rol_id integer NOT NULL REFERENCES public.rol(rol_id),
    CONSTRAINT usuario_correo_dominio_chk CHECK (lower(usuario_correo) LIKE '%@brewflow.cl')
);

-- =============================================================
-- 4. Tablas de configuración base
-- =============================================================

CREATE TABLE public.unidad_medida_personalizada (
    unidad_medida_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidad_medida_codigo varchar(30) NOT NULL UNIQUE,
    unidad_medida_nombre varchar(100) NOT NULL,
    unidad_medida_clasificacion varchar(50) NOT NULL,
    unidad_medida_estado varchar(20) NOT NULL DEFAULT 'activo',
    CONSTRAINT unidad_medida_clasificacion_chk CHECK (unidad_medida_clasificacion IN ('masa', 'volumen', 'unidad', 'contenedor', 'otro')),
    CONSTRAINT unidad_medida_estado_chk CHECK (unidad_medida_estado IN ('activo', 'inactivo'))
);

CREATE TABLE public.proveedor (
    proveedor_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proveedor_rut varchar(20) NOT NULL UNIQUE,
    proveedor_nombre varchar(100) NOT NULL,
    proveedor_nombre_contacto varchar(100),
    proveedor_telefono_contacto varchar(20),
    proveedor_correo_contacto varchar(150),
    proveedor_condiciones_comerciales text,
    proveedor_estado varchar(20) NOT NULL DEFAULT 'activo',
    lote_id integer,
    CONSTRAINT proveedor_estado_chk CHECK (proveedor_estado IN ('activo', 'inactivo'))
);

CREATE TABLE public.ubicacion_bodega (
    ubicacion_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ubicacion_codigo varchar(50) NOT NULL UNIQUE,
    ubicacion_nombre varchar(100) NOT NULL,
    ubicacion_tipo varchar(30) NOT NULL,
    ubicacion_padre_id integer REFERENCES public.ubicacion_bodega(ubicacion_id) ON DELETE SET NULL,
    ubicacion_estado varchar(20) NOT NULL DEFAULT 'activo',
    CONSTRAINT ubicacion_tipo_chk CHECK (ubicacion_tipo IN ('zona', 'estante', 'nivel', 'posicion')),
    CONSTRAINT ubicacion_estado_chk CHECK (ubicacion_estado IN ('activo', 'inactivo')),
    CONSTRAINT ubicacion_no_autorreferencia_chk CHECK (ubicacion_padre_id IS NULL OR ubicacion_padre_id <> ubicacion_id)
);

-- =============================================================
-- 5. Tablas de productos, insumos, lotes y movimientos
-- =============================================================

CREATE TABLE public.producto (
    producto_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_codigo varchar(50) NOT NULL UNIQUE,
    producto_nombre varchar(100) NOT NULL,
    producto_precio numeric(10,2) NOT NULL DEFAULT 0,
    producto_categoria varchar(100),
    producto_estado varchar(20) NOT NULL DEFAULT 'activo',
    producto_unidad_medida_id integer NOT NULL REFERENCES public.unidad_medida_personalizada(unidad_medida_id),
    producto_stock_actual numeric(12,2) NOT NULL DEFAULT 0,
    CONSTRAINT producto_estado_chk CHECK (producto_estado IN ('activo', 'inactivo')),
    CONSTRAINT producto_precio_chk CHECK (producto_precio >= 0),
    CONSTRAINT producto_stock_actual_chk CHECK (producto_stock_actual >= 0)
);

CREATE TABLE public.insumo (
    insumo_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_nombre varchar(100) NOT NULL,
    insumo_stock_actual integer NOT NULL DEFAULT 0,
    insumo_stock_critico integer NOT NULL DEFAULT 0,
    insumo_unidad_medida public.unidad_medida_enum NOT NULL,
    producto_id integer REFERENCES public.producto(producto_id),
    CONSTRAINT insumo_stock_actual_chk CHECK (insumo_stock_actual >= 0),
    CONSTRAINT insumo_stock_critico_chk CHECK (insumo_stock_critico >= 0)
);

CREATE TABLE public.lote (
    lote_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lote_codigo varchar(50) NOT NULL UNIQUE,
    lote_cantidad_ingresada numeric(12,2) NOT NULL,
    lote_cantidad_disponible numeric(12,2) NOT NULL DEFAULT 0,
    lote_fecha_recepcion date NOT NULL DEFAULT CURRENT_DATE,
    lote_fecha_vencimiento date,
    producto_id integer NOT NULL REFERENCES public.producto(producto_id),
    proveedor_id integer NOT NULL REFERENCES public.proveedor(proveedor_id),
    ubicacion_id integer REFERENCES public.ubicacion_bodega(ubicacion_id),
    insumo_id integer REFERENCES public.insumo(insumo_id),
    CONSTRAINT lote_cantidad_ingresada_chk CHECK (lote_cantidad_ingresada > 0),
    CONSTRAINT lote_cantidad_disponible_chk CHECK (lote_cantidad_disponible >= 0),
    CONSTRAINT lote_fecha_vencimiento_chk CHECK (lote_fecha_vencimiento IS NULL OR lote_fecha_vencimiento > lote_fecha_recepcion)
);

ALTER TABLE public.proveedor
    ADD CONSTRAINT proveedor_lote_id_fkey
    FOREIGN KEY (lote_id) REFERENCES public.lote(lote_id) ON DELETE SET NULL;

CREATE TABLE public.producto_proveedor (
    producto_id integer NOT NULL REFERENCES public.producto(producto_id) ON DELETE CASCADE,
    proveedor_id integer NOT NULL REFERENCES public.proveedor(proveedor_id) ON DELETE CASCADE,
    fecha_asociacion date NOT NULL DEFAULT CURRENT_DATE,
    estado varchar(20) NOT NULL DEFAULT 'activo',
    PRIMARY KEY (producto_id, proveedor_id),
    CONSTRAINT producto_proveedor_estado_chk CHECK (estado IN ('activo', 'inactivo'))
);

CREATE TABLE public.movimiento_stock (
    movimiento_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movimiento_tipo varchar(20) NOT NULL,
    movimiento_motivo varchar(30),
    movimiento_fecha timestamp without time zone NOT NULL DEFAULT now(),
    movimiento_cantidad numeric(12,2) NOT NULL,
    movimiento_observacion text,
    producto_id integer NOT NULL REFERENCES public.producto(producto_id),
    lote_id integer REFERENCES public.lote(lote_id),
    proveedor_id integer REFERENCES public.proveedor(proveedor_id),
    usuario_id integer REFERENCES public.usuario(usuario_id),
    CONSTRAINT movimiento_tipo_chk CHECK (movimiento_tipo IN ('ingreso', 'salida')),
    CONSTRAINT movimiento_motivo_chk CHECK (movimiento_motivo IS NULL OR movimiento_motivo IN ('venta', 'consumo_interno', 'merma', 'descarte')),
    CONSTRAINT movimiento_cantidad_chk CHECK (movimiento_cantidad > 0)
);

CREATE TABLE public.merma (
    merma_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merma_cantidad integer NOT NULL,
    merma_fecha date NOT NULL DEFAULT CURRENT_DATE,
    merma_motivo public.merma_motivo_enum NOT NULL,
    merma_observacion varchar(255),
    insumo_id integer NOT NULL REFERENCES public.insumo(insumo_id),
    CONSTRAINT merma_cantidad_chk CHECK (merma_cantidad > 0)
);

CREATE TABLE public.receta (
    receta_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receta_cantidad numeric(10,2) NOT NULL,
    producto_id integer NOT NULL REFERENCES public.producto(producto_id),
    CONSTRAINT receta_cantidad_chk CHECK (receta_cantidad > 0)
);

-- =============================================================
-- 6. Tablas operativas heredadas: mesas, pedidos, pagos y caja
-- =============================================================

CREATE TABLE public.mesa (
    mesa_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_numero integer NOT NULL UNIQUE,
    mesa_estado public.mesa_estado_enum NOT NULL DEFAULT 'disponible',
    mesa_capacidad integer NOT NULL,
    usuario_id integer REFERENCES public.usuario(usuario_id),
    CONSTRAINT mesa_capacidad_chk CHECK (mesa_capacidad > 0)
);

CREATE TABLE public.pedido (
    pedido_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_fecha_hora timestamp without time zone NOT NULL DEFAULT now(),
    pedido_estado public.pedido_estado_enum NOT NULL DEFAULT 'pendiente',
    pedido_total_neto numeric(10,2) NOT NULL DEFAULT 0,
    mesa_id integer NOT NULL REFERENCES public.mesa(mesa_id),
    CONSTRAINT pedido_total_neto_chk CHECK (pedido_total_neto >= 0)
);

CREATE TABLE public.detalle_pedido (
    pedido_id integer PRIMARY KEY REFERENCES public.pedido(pedido_id),
    pedido_fecha_hora timestamp without time zone NOT NULL DEFAULT now(),
    pedido_estado public.pedido_estado_enum DEFAULT 'pendiente',
    pedido_total_neto numeric(10,2) DEFAULT 0,
    insumo_id integer REFERENCES public.insumo(insumo_id)
);

CREATE TABLE public.registro_pago (
    registro_pago_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_pago_monto numeric(10,2) NOT NULL,
    registro_pago_metodo public.pago_metodo_enum,
    registro_pago_estado_dte public.pago_estado_enum NOT NULL DEFAULT 'pendiente',
    pedido_id integer NOT NULL REFERENCES public.pedido(pedido_id),
    CONSTRAINT registro_pago_monto_chk CHECK (registro_pago_monto >= 0)
);

CREATE TABLE public.arqueo_caja (
    arqueo_caja_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    arqueo_caja_fecha_cierre timestamp without time zone NOT NULL DEFAULT now(),
    arqueo_caja_monto_esperado numeric(10,2) NOT NULL,
    arqueo_caja_monto_declarado numeric(10,2) NOT NULL,
    arqueo_caja_discrepancia_porcentual numeric(5,2),
    registro_pago_id integer REFERENCES public.registro_pago(registro_pago_id),
    CONSTRAINT arqueo_monto_esperado_chk CHECK (arqueo_caja_monto_esperado >= 0),
    CONSTRAINT arqueo_monto_declarado_chk CHECK (arqueo_caja_monto_declarado >= 0)
);